- alias: Notification security - If New Devices
  trigger:
    - platform: event
      event_type: device_tracker_new_device
  action:
    - service: notify.slack
      data:
        message: "New device: {{trigger.event.data.entity_id}}"