language: python
python:
  - "3.5"
before_install:
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install homeassistant
  - pip install --user yamllint
script:
  - yamllint .
  - hass -c . --script check_config --info all

notifications:
  email:
    on_failure: change