
 ############################################
 #  Home assistant maintanance automations  #
 ############################################

 #Pull config when travis build succedeed
  - id: pull_config
    alias: Pull hass configuration when Travis build succeded
    trigger:
    - platform: state
      entity_id: binary_sensor.travis_status
      to: 'on'
    action:
    - service: shell_command.pull_git_conf
    - delay: '00:00:10'
    - service: homeassistant.restart

# Restart mopidy service every hour when it's no playing
  - id: restart_mopidy
    alias: Restart mopidy service 
    trigger:
    - platform: time
      minutes: 00
      seconds: 00
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: 'media_player.salon'
        state: 'off'
      - condition: state
        entity_id: 'media_player.salon'
        state: 'paused'      
    action:
    - service: shell_command.restart_mopidy


#######################
#  Snips automations  #
#######################

# Saying current temperature via snips
  - id: temperature
    alias: Snips - say temperature
    trigger:
    - platform: mqtt
      topic: hermes/intent/mi_checinski:temperature
    action:
    - service: mqtt.publish
      data:
        topic: hermes/dialogueManager/endSession
        payload_template: "{{ 'text': 'Inside is {{ states.sensor.dht_sensor_temperature }} celsius degrees.', 'session_id': 'c96711cb-0932-458c-97bf-d0eeb3266c7e' }}"

# Turn off mopidy when snips is saying
  - id: off_mopidy
    alias: Snips - Turn mopidy off when Snips saying
    trigger:
    - platform: mqtt
      topic: hermes/dialogueManager/endSession
    action:
    - service: media_player.turn_off

##################################################################    
#  Sleep automations (now fired by Sleep As Android and Tasker)  #
##################################################################

# Automation when going into sleep
  - id: sleep_on
    alias: Sleep - power off 
    trigger:
    - platform: state
      entity_id: binary_sensor.sleep
      to: 'on'
    condition:
      condition: state
      entity_id: input_boolean.michal_home
      state: 'on'      
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.b2, switch.b1, switch.stereo_switch

# Automation after wake up
  - id: sleep_off
    alias: Sleep - awake 
    trigger:
    - platform: state
      entity_id: binary_sensor.sleep
      from: 'on'
      to: 'off'  
    condition:
      condition: state
      entity_id: input_boolean.michal_home
      state: 'on' 
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.b2

# Automation when alarm is ringing
  - id: alarm_on
    alias: Sleep - alarm goes off 
    trigger:
    - platform: state
      entity_id: binary_sensor.sleep_alarm
      to: 'on'   
    action:
      - service: light.turn_on
        data:
          entity_id: light.bed_lamp
      - service: rest_command.play_wakeup_playlist
      - delay: '00:00:10'
      - service: homeassistant.turn_off
        data:
          entity_id: binary_sensor.sleep_alarm
      - delay: '00:05:00'
      - service: light.turn_off
        data:
          entity_id: light.bed_lamp

###############################################
#  Set input boolean if user at home or away  #
###############################################

# Away home
  - id: away
    alias: Presence - turn off boolean when leaving home
    trigger:
    - platform: state
      entity_id: device_tracker.google_maps_102169435937546415265
      to: 'not_home'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.michal_home
      - service: script.ifttt_notify
        data_template:
          value1: "Wyszedłeś z domu"
          value2: "Home assistant wykrył, że wyszedłeś z domu."

# At home
  - id: at_home
    alias: Presence - turn on boolean when at home
    trigger:
    - platform: state
      entity_id: device_tracker.google_maps_102169435937546415265
      to: 'home'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.michal_home
      - service: script.ifttt_notify
        data_template:
          value1: "Wszedłeś do domu"
          value2: "Home assistant wykrył, że jesteś w domu."

########################
# Presence automations #
########################

# Fire away home script when leaving home
  - id: away_home_script
    alias: Presence - away home
    trigger:
    - platform: state
      entity_id: input_boolean.michal_home
      from: 'on'
      to: 'off'   
    action:
      - service: script.away_home

########################################################
#  Led brightness automations (fired by input_select)  #
########################################################   

  - id: led_100
    alias: LED - brightness 100%
    trigger:
      platform: state
      entity_id: input_select.led_brightness_select
      to: 100%
    action:
      - service: shell_command.led_brightness_100
      - service: input_number.set_value
        data:
          entity_id: input_number.led_brightness_slider
          value: 100
      
  - id: led_50
    alias: LED - brightness 50%
    trigger:
      platform: state
      entity_id: input_select.led_brightness_select
      to: 50%
    action:
      - service: shell_command.led_brightness_50
      - service: input_number.set_value
        data:
          entity_id: input_number.led_brightness_slider
          value: 50
      
  - id: led_25
    alias: LED - brightness 25%
    trigger:
      platform: state
      entity_id: input_select.led_brightness_select
      to: 25%
    action:
      - service: shell_command.led_brightness_25
      - service: input_number.set_value
        data:
          entity_id: input_number.led_brightness_slider
          value: 25

##############################
#  Notification automations  #
##############################

# Notify when outside temperature sensor is dead
  - id: temperature_sensor_battery_dead
    alias: Notification - temperature sensor is not sending data
    trigger:
      platform: mqtt
      topic: 'outside/temperature'
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: script.notify_temperature_dead
      - delay: '00:00:10'
      - service: homeassistant.turn_on
        data:
          entity_id: script.notify_temperature_dead

# Notify when new home assistant version is live
  - id: update_notification
    alias: Notification - hass update available
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      - service: script.ifttt_notify
        data_template:
          value1: "Update"
          value2: "There is a new Home Assistant release available."

###############################
#  Vacation Mode Automations  #
###############################

# Turn on Vacation Mode when Gone 24 Hours
  - id: vacation_on
    alias: Vacation - turn on when Gone 24 Hours
    trigger:
      platform: state
      entity_id: input_boolean.michal_home
      to: 'off'
      for:
        hours: 24
        minutes: 0
        seconds: 0
#    condition:
#      - condition: state
#        entity_id: input_boolean.disable_home_away
#        state: 'off'
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.vacation_mode
      - service: script.ifttt_notify
        data_template:
          value1: "Wakacje"
          value2: "Wyjechałeś na wakacje i hass to wykrył"

# Turn off Vacation Mode when Home
  - id: vacation_off
    alias: Vacation - turn off when Home
    trigger:
      platform: state
      entity_id: input_boolean.michal_home
      from: 'off'
      to: 'on'
#    condition:
#      - condition: state
#        entity_id: input_boolean.disable_home_away
#        state: 'off'
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.vacation_mode
      - service: script.ifttt_notify
        data_template:
          value1: "Wakacje"
          value2: "Wróciłeś z wakacji i hass to wykrył"


###################################
#  Livingroom stereo automations  #
###################################

# Turn on stereo when Mopidy starts to play
  - id: stereo_on_mopidy
    alias: Livingroom stereo - turn on when mopidy starts to play
    trigger:
      - platform: state
        entity_id: media_player.salon
        to: 'playing'
    condition:
      - condition: state
        entity_id: switch.stereo_switch
        state: 'off'
    action:
      - service: media_player.media_pause
        data:
          entity_id: media_player.salon 
      - service: switch.toggle
        data:
          entity_id: switch.stereo_switch
      - delay: '00:00:05'
      - service: media_player.media_play
        data:
          entity_id: media_player.salon 

# Turn stereo off after 10 minutes of inactivity
  - id: stereo_off_10_minutes_no_mopidy
    alias: Livingroom stereo - turn off when mopidy not playing for 10 minutes
    trigger:
      - platform: state
        entity_id: media_player.salon
        to: 'off'
        for:
          hours: 0
          minutes: 10
          seconds: 0
      - platform: state
        entity_id: media_player.salon
        to: 'paused'
        for:
          hours: 0
          minutes: 10
          seconds: 0
    condition:
      - condition: state
        entity_id: switch.stereo_switch
        state: 'on'
    action:
      service: switch.toggle
      data:
        entity_id: switch.stereo_switch

##################################
# Audio Notification Automations #
##################################

# Welcome when arrive at home
  - id: welcomme_home
    alias: Audio Notification - welcome home
    trigger:
      - platform: state
        entity_id: input_boolean.michal_home
        from: 'off'
        to: 'on'
    condition:
      - condition: time
        after: '09:00'
        before: '22:00'
    action:
      - delay: '00:05:00'
      - service: script.turn_on
        entity_id: script.say
        data:
          variables:
            volume: '0.8'
            what: 'Witaj w domu, Michał'

##########################
# Phone call automations #
##########################
  
# Stop playback on phonecall
  - id: phone_ring
    alias: Phone - ringing pause music playback
    trigger:
      - platform: state
        entity_id: binary_sensor.phone_call
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: media_player.salon
        state: 'playing'
    action:
      - service: media_player.media_pause
        data:
          entity_id: media_player.salon
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.was_playing

# Resume playback after finishing the call
  - id: phone_not_ring
    alias: Phone - resume music after
    trigger:
      - platform: state
        entity_id: binary_sensor.phone_call
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.was_playing
        state: 'on'
    action:
      - service: media_player.media_play
        data:
          entity_id: media_player.salon 
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.was_playing

##########################
# Returning home actions #
##########################

# Turn on all lights for two minutes when enter into dark home (after sunset)
  - id: went_dark_home
    alias: 'Lights - turn on when entering dark house (after sunset)'
    trigger:
      - platform: state
        entity_id: input_boolean.michal_home
        from: 'off'
        to: 'on'
    condition:
      - condition: sun
        after: sunset
        after_offset: "-1:00:00"
    action:
      - delay: '00:02:30'
      - service: homeassistant.turn_on
        entity_id: group.all_lights
      - delay: '00:02:00'
      - service: homeassistant.turn_off
        entity_id: group.all_lights

##########################
# Guest mode automations #
##########################

# Turn off sleep automations when guest mode enabled

  - id: guest_mode_on
    alias: Guest mode - turn on
    trigger:
      - platform: state
        entity_id: input_boolean.guest_mode
        from: 'off'
        to: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: automation.sleep__alarm_goes_off, automation.sleep__awake,  automation.sleep__power_off

# Turn on sleep automations when guest mode disabled
 - id: guest_mode_off
    alias: Guest mode - turn off
    trigger:
      - platform: state
        entity_id: input_boolean.guest_mode
        from: 'on'
        to: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: automation.sleep__alarm_goes_off, automation.sleep__awake,  automation.sleep__power_off