
 ############################################
 #  Home assistant maintanance automations  #
 ############################################

 #Pull config when travis build succedeed
  - id: pull_config
    alias: Pull hass configuration when Travis build succeded
    trigger:
    - platform: state
      entity_id: binary_sensor.travis_status
      to: 'on'
    action:
    - service: shell_command.pull_git_conf
    - delay: '00:00:10'
    - service: homeassistant.restart

# Restart mopidy service every hour when it's no playing
  - id: restart_mopidy
    alias: Restart mopidy service 
    trigger:
    - platform: time
      minutes: 00
      seconds: 00
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: 'media_player.salon'
        state: 'off'
      - condition: state
        entity_id: 'media_player.salon'
        state: 'paused'      
    action:
    - service: shell_command.restart_mopidy


#######################
#  Snips automations  #
#######################

# Saying current temperature via snips
  - id: temperature
    alias: Say temperature
    trigger:
    - platform: mqtt
      topic: hermes/intent/mi_checinski:temperature
    action:
    - service: mqtt.publish
      data:
        topic: hermes/dialogueManager/endSession
        payload_template: "{{ 'text': 'Inside is {{ states.sensor.dht_sensor_temperature }} celsius degrees.', 'session_id': 'c96711cb-0932-458c-97bf-d0eeb3266c7e' }}"

# Turn off mopidy when snips is saying
  - id: off_mopidy
    alias: Turn mopidy off when saying via Snips
    trigger:
    - platform: mqtt
      topic: hermes/dialogueManager/endSession
    action:
    - service: media_player.turn_off

##################################################################    
#  Sleep automations (now fired by Sleep As Android and Tasker)  #
##################################################################

# Automation when going into sleep
  - id: sleep_on
    alias: Power off when sleep 
    trigger:
    - platform: state
      entity_id: binary_sensor.sleep
      to: 'on'
    condition:
      condition: state
      entity_id: input_boolean.michal_home
      state: 'on'      
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.b2, switch.b1

# Automation after wake up
  - id: sleep_off
    alias: Power computer on when no sleep 
    trigger:
    - platform: state
      entity_id: binary_sensor.sleep
      from: 'on'
      to: 'off'  
    condition:
      condition: state
      entity_id: input_boolean.michal_home
      state: 'on' 
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.b2

# Automation when alarm is ringing
  - id: alarm_on
    alias: Lights up when alarm goes off 
    trigger:
    - platform: state
      entity_id: binary_sensor.sleep_alarm
      to: 'on'   
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.b1
      - delay: '00:00:10'
      - service: homeassistant.turn_off
        data:
          entity_id: binary_sensor.sleep_alarm
      - delay: '00:05:00'
      - service: switch.turn_off
        data:
          entity_id: switch.b1
          
  - id: iron_off_when_away
    alias: Turn off iron switch when leaving home
    trigger:
    - platform: state
      entity_id: input_boolean.michal_home
      from: 'on'
      to: 'off'   
    action:
      - service: script.away_home

###############################################
#  Set input boolean if user at home or away  #
###############################################

# Away home
  - id: away
    alias: Turn off off boolean when leaving home
    trigger:
    - platform: state
      entity_id: device_tracker.google_maps_102169435937546415265
      to: 'not_home'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.michal_home

# At home
  - id: at_home
    alias: Turn on boolean when at home
    trigger:
    - platform: state
      entity_id: device_tracker.google_maps_102169435937546415265
      to: 'home'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.michal_home

########################################################
#  Led brightness automations (fired by input_select)  #
########################################################   

  - id: led_100
    alias: LED brightness 100%
    trigger:
      platform: state
      entity_id: input_select.led_brightness_select
      to: 100%
    action:
      - service: shell_command.led_brightness_100
      - service: input_number.set_value
        data:
          entity_id: input_number.led_brightness_slider
          value: 100
      
  - id: led_50
    alias: LED brightness 50%
    trigger:
      platform: state
      entity_id: input_select.led_brightness_select
      to: 50%
    action:
      - service: shell_command.led_brightness_50
      - service: input_number.set_value
        data:
          entity_id: input_number.led_brightness_slider
          value: 50
      
  - id: led_25
    alias: LED brightness 25%
    trigger:
      platform: state
      entity_id: input_select.led_brightness_select
      to: 25%
    action:
      - service: shell_command.led_brightness_25
      - service: input_number.set_value
        data:
          entity_id: input_number.led_brightness_slider
          value: 25

##############################
#  Notification automations  #
##############################

# Notify when outside temperature sensor is dead
  - id: temperature_sensor_battery_dead
    alias: Notify when temperature sensor is not sending data
    trigger:
      platform: mqtt
      topic: 'outside/temperature'
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: script.notify_temperature_dead
      - delay: '00:00:10'
      - service: homeassistant.turn_on
        data:
          entity_id: script.notify_temperature_dead

# Notify when new home assistant version is live
  - id: update_notification
    alias: Notification when hass update available
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      - service: script.ifttt_notify
        data_template:
          value1: "Update"
          value2: "There is a new Home Assistant release available."

###############################
#  Vacation Mode Automations  #
###############################

# Turn on Vacation Mode when Gone 24 Hours
  - id: vacation_on
    alias: Vacation - Turn on when Gone 24 Hours
    trigger:
      platform: state
      entity_id: input_boolean.michal_home
      to: 'off'
      for:
        hours: 24
        minutes: 0
        seconds: 0
#    condition:
#      - condition: state
#        entity_id: input_boolean.disable_home_away
#        state: 'off'
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.vacation_mode

# Turn off Vacation Mode when Home
  - id: vacation_off
    alias: Vacation - Turn off when Home
    trigger:
      platform: state
      entity_id: input_boolean.michal_home
      from: 'off'
      to: 'on'
#    condition:
#      - condition: state
#        entity_id: input_boolean.disable_home_away
#        state: 'off'
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.vacation_mode


###################################
#  Livingroom stereo automations  #
###################################

# Turn on stereo when Mopidy starts to play
  - id: stereo_on_mopidy
    alias: Turn on stereo system when mopidy starts to play
    trigger:
      - platform: state
        entity_id: media_player.salon
        to: 'playing'
    condition:
      - condition: state
        data:
          entity_id: switch.stereo_switch
          state: 'off'
    action:
      service: switch.toggle
      data:
        entity_id: switch.stereo_switch

# Turn stereo off after 10 minutes of inactivity
  - id: stereo_off_10_minutes_no_mopidy
    alias: Turn stereo off when mopidy not playing for 10 minutes
    trigger:
      - platform: state
        entity_id: media_player.salon
        to: 'off'
        for:
          minutes: 10
          seconds: 0
      - platform: state
        entity_id: media_player.salon
        to: 'paused'
        for:
          minutes: 10
          seconds: 0
    condition:
      - condition: state
        data:
          entity_id: switch.stereo_switch
          state: 'off'
    action:
      service: switch.toggle
      data:
        entity_id: switch.stereo_switch