trigger:
  - master

schedules:
- cron: "0 0 * * *"
  displayName: Daily build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job:
    displayName: 'Check HomeAssistant config Latest'
    steps:
      - template: azure-pipeline-templates/pre-hass-steps.yml

      - script: pip install --upgrade homeassistant

      - script: |
          hass --version
          hass -c . --script check_config --info all
        displayName: 'test hass config'

  - job:
    displayName: 'Check HomeAssistant config pre'
    continueOnError: true
    steps:
      - template: azure-pipeline-templates/pre-hass-steps.yml

      - script: pip install --upgrade --pre homeassistant

      - script: |
          hass --version
          hass -c . --script check_config --info all
        displayName: 'test hass config'
