#######################
# Climate Thermostats #
#######################


- platform: generic_thermostat
  name: Living Room
  heater: input_boolean.fake_heater
  target_sensor: sensor.livingroom_temperature
  
- platform: generic_thermostat
  name: Bedroom
  heater: input_boolean.fake_heater
  target_sensor: sensor.bedroom_temperature

- platform: generic_thermostat
  name: inside
  heater: input_boolean.fake_heater
  target_sensor: sensor.temperature_inside

- platform: generic_thermostat
  name: Outside
  heater: input_boolean.fake_heater
  target_sensor: sensor.temperature_outside