default_config:

homeassistant:
  name: Dom
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 110
  unit_system: metric
  time_zone: Europe/Warsaw
  external_url: !secret base_url
  internal_url: "http://192.168.1.100:8123"

  customize: !include customize.yaml

  auth_providers:
    - type: homeassistant

recorder: !include recorder.yaml

frontend:

config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5

updater:

conversation:

history:

logbook:

map:

sun:

system_health:

person:

tts:
  - platform: google_translate
    service_name: google_say
    language: 'pl'

sensor: !include_dir_merge_list entities/sensors
binary_sensor: !include_dir_merge_list entities/binary_sensors
switch: !include_dir_merge_list entities/switch
light: !include_dir_merge_list entities/light
group: !include groups.yaml
automation manual: !include_dir_merge_list automations
automation ui: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
scene: !include scenes.yaml
camera: !include camera.yaml

# input
input_select: !include entities/input_select.yaml
input_number: !include entities/input_number.yaml
input_boolean: !include entities/input_boolean.yaml

google_assistant: !include google_assistant.yaml

proximity: !include proximity.yaml

mobile_app:

webostv: !include integrations/webostv.yaml

media_player:

spotify:
  client_id: !secret spotify_client
  client_secret: !secret spotify_secret


panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: https://hass.checinski.xyz:9541