version: '3'

services:
  home-assistant:
    image: homeassistant/home-assistant:latest
    container_name: "hass"
    restart: always
    volumes:
      - .\:/config
    ports:
      - 8123:8123
    environment:
      - TZ=Europe/Warsaw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
      interval: 30s
      timeout: 10s
      retries: 6
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     mqtt:
  #       condition: service_started
  # db:
  #  image: postgres
  #  restart: on-failure
  # mqtt:
  #  image: eclipse-mosquitto:latest
  #  container_name: "MQTT"
  #  restart: always
  #  ports:
  #     - 1883:1883
  #   volumes:
  #     - /home/$USER/docker_files/mqtt/data:/mosquitto/data
  #     - /home/$USER/docker_files/mqtt/config:/mosquitto/config
  #     - /home/$USER/docker_files/mqtt/log:/mosquitto/log
  #   network_mode: "host"
  #   environment:
  #     - TZ=Europe/Warsaw