############
# Switches #
############

- platform: rpi_rf
  gpio: 15
  switches:
    A1:
      code_on: 14013452
      code_off: 14013451
    B1:
      code_on: 7721996
      code_off: 7721995
      signal_repetitions: 30
    B2:
      code_on: 7697412
      code_off: 7697411
    B3:
      code_on: 7691276
      code_off: 7691275

- platform: mqtt
  name: "Stereo mqtt"
  command_topic: "stereo/on"
  icon: mdi:speaker

- platform: template
  switches:
    stereo:
      friendly_name: "Stereo"
      value_template: "{{ is_state('switch.stereo_mqtt', 'on') }}"
      turn_on:
        service: script.stereo_on
      turn_off:
        service: script.stereo_off
      icon_template: mdi:speaker
