title: My Lovely Home Automation
views:

  - title: Home
    icon: mdi:home
    cards:
      - type: glance
        title: Michał state
        show_header_toggle: false
        entities:
          - device_tracker.google_maps_102169435937546415265
          - device_tracker.oneplus
          - group.michal_home
          - proximity.home     

      - type: entities
        title: Michal state
        show_header_toggle: false
        entities:
          - input_select.michal_status
          - input_boolean.guest_mode
          - input_boolean.vacation_mode

      - type: entities
        title: Temperature
        show_header_toggle: false
        entities:
          - sensor.temperature_outside
          - sensor.dht_sensor_temperature


  - title: Living room
    icon: mdi:sofa
    cards:
      - type: media-control
        entity: media_player.spotify

      - type: media-control
        entity: media_player.tv

      - type: entities
        title: DHT
        show_header_toggle: false
        entities:
          - sensor.dht_sensor_humidity
          - sensor.dht_sensor_temperature

      - type: entities
        title: Switches
        show_header_toggle: true
        entities:
          - switch.b3
          - switch.stereo

      - type: entities
        title: Light
        show_header_toggle: true
        entities:
          - light.rtv_led

  - title: Bedroom
    icon: mdi:hotel
    cards:
      - type: glance
        title: Lights
        show_header_toggle: true
        entities:
          - light.bed_lamp

      - type: glance
        title: THINKPAD status
        show_header_toggle: false
        entities:
          - binary_sensor.thinkpad

  - title: Climate
    cards:
      - type: glance
        title: Sun
        show_header_toggle: true
        entities:
          - sun.sun

      - type: glance
        title: Smog
        show_header_toggle: false
        entities:
          - sensor.waqi_komunikacyjna_warszawa_mazowieckie_poland
      
      - type: glance
        title: Temperature
        show_header_toggle: false
        entities:
          - sensor.temperature_outside
          - sensor.dht_sensor_humidity
          - sensor.dht_sensor_temperature

      - type: entities
        title: OWM weather
        show_header_toggle: false
        entities:
          - sensor.owm_condition
          - sensor.owm_rain
          - sensor.owm_snow
          - sensor.owm_temperature

      - type: entities
        title: YR weather
        show_header_toggle: false
        entities:
          - sensor.yr_weather_cloudiness
          - sensor.yr_weather_fog
          - sensor.yr_weather_humidity
          - sensor.yr_weather_precipitation
          - sensor.yr_weather_pressure
          - sensor.yr_weather_temperature

  - title: Config
    icon: mdi:home-assistant
    cards:

      - type: entities
        title: Manual input
        show_header_toggle: false
        entities:
          - input_boolean.guest_mode
          - input_boolean.guests_arriving_mode
          - input_boolean.sleep
          - input_boolean.vacation_mode
          - input_boolean.romantic_dance_mode
          - input_boolean.romantic_mode

      - type: glance
        title: Hass details
        entities:
          - binary_sensor.needs_update
          - binary_sensor.travis_status
          - binary_sensor.newest_commit
          - sensor.uptime

      - type: vertical-stack
        cards:
          - type: glance
            title: At home
            entities:
              - sensor.home_today
              - sensor.home_week
              - sensor.home_month
          - type: glance
            title: Using computer
            entities:
              - sensor.computer_today
              - sensor.computer_week
              - sensor.computer_month
          - type: glance
            title: Watching tv
            entities:
              - sensor.tv_today
              - sensor.tv_week
              - sensor.tv_month

      - type: vertical-stack
        cards:
          - type: glance
            title: Server Load
            entities:
              - entity: sensor.load_1m
                icon: mdi:speedometer
              - entity: sensor.load_5m
                icon: mdi:speedometer
              - entity: sensor.load_15m
                icon: mdi:speedometer
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.processor_use
                name: Processor
                hours_to_show: 24
                graph: line
                detail: 1
              - type: sensor
                entity: sensor.memory_use_percent
                name: Memory
                hours_to_show: 24
                graph: line
                detail: 1

      # - type: entities
      #   title: Batteries
      #   show_header_toggle: true
      #   entities:
      #     - sensor.bathroom_leak_battery
      #     - sensor.door_battery
      #     - sensor.outside_battery

      - type: entities
        title: Home Assistant Stats
        show_header_toggle: false
        entities:
          - entity: sensor.tracker_count
            icon: mdi:cellphone-link
            name: Number of Network Devices
          - entity: sensor.lights_count
            icon: mdi:lightbulb
          - entity: sensor.binary_sensor_count
            icon: mdi:nintendo-switch
          - entity: sensor.switch_count
            icon: mdi:toggle-switch
          - entity: sensor.automation_count
            icon: mdi:home-assistant
          - entity: sensor.script_count
            icon: mdi:script-text-outline
          - entity: sensor.sensor_count
            icon: mdi:gauge
          - entity: sensor.zwave_count
            icon: mdi:z-wave

  - title: Power
    icon: mdi:flash
    cards:
      - type: glance
        title: Switches
        show_header_toggle: true
        entities:
          # - switch.a1
          # - switch.b1
          # - switch.b2
          - switch.b3
          - switch.stereo

      - type: glance
        title: Lights
        show_header_toggle: true
        entities:
          - light.bed_lamp
          - light.rtv_led
          - switch.led_fix

      - type: entities
        title: Force led
        show_header_toggle: true
        entities:
          - script.force_led_on
          - script.force_led_off