- alias: Vacuum start via notification
  trigger:
    - event_data:
        action: vacuum_on
      event_type: mobile_app_notification_action
      platform: event
  action:
    - service: homeassistant.turn_off
      data_template:
        entity_id: script.vacuum_stop
    - service: automation.trigger
      data_template:
        entity_id: automation.vacuum_on


- alias: Vacuum stop via notification
  trigger:
    - event_data:
        action: vacuum_off
      event_type: mobile_app_notification_action
      platform: event
  action:
    - service: vacuum.stop
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
  # Dont know if next line is necessary
    - service: vacuum.return_to_base
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner