- alias: Guest mode - off via notification
  trigger:
    - event_data:
        action: guest_mode_off
      event_type: mobile_app_notification_action
      platform: event
  action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: input_boolean.guest_mode