######################################
#  Notification buttons automations  #
######################################

- alias: Vacuum - on via notification
  trigger:
    - event_data:
        action: vacuum_on
      event_type: html5_notification.clicked
      platform: event
  action:
    - service: homeassistant.turn_off
      data_template:
        entity_id: script.vacuum_stop
    - service: automation.trigger
      data_template:
        entity_id: automation.vacuum_on

- alias: Guest mode - off via notification
  trigger:
    - event_data:
        action: guest_mode_off
      event_type: html5_notification.clicked
      platform: event
  action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: input_boolean.guest_mode

- alias: HA - update via notification
  trigger:
    - event_data:
        action: update_ha
      event_type: html5_notification.clicked
      platform: event
  action:
    - service: shell_command.update_ha