######################
# Living room lights #
######################

- platform: mqtt
  name: rtv led
  command_topic: "cmnd/livingroomled/POWER1"
  state_topic: "stat/livingroomled/RESULT"
  value_template: "{{ value_json.POWER1 }}"
  availability_topic: "tele/livingroomled/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: tv led
  command_topic: "cmnd/livingroomled/POWER2"
  state_topic: "stat/livingroomled/RESULT"
  value_template: "{{ value_json.POWER2 }}"
  availability_topic: "tele/livingroomled/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
