###################
# Stereo switches #
###################


- platform: template
  switches:
    stereo:
      friendly_name: "Stereo"
      value_template: "{{ is_state('binary_sensor.pioneer_stereo_state', 'on') }}"
      turn_on:
        - service: switch.toggle
          target:
            entity_id: switch.pioneer_stereo
        - delay: '00:00:01'
        - service: homeassistant.update_entity
          target:
            entity_id: sensor.living_room_appliances_current_consumption
      turn_off:
        - service: switch.toggle
          target:
            entity_id: switch.pioneer_stereo
        - delay: '00:00:01'
        - service: homeassistant.update_entity
          target:
            entity_id: sensor.living_room_appliances_current_consumption
      icon_template: mdi:speaker
