homeassistant:
  name: Dom
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 110
  unit_system: metric
  time_zone: Europe/Warsaw
  external_url: !secret base_url
  internal_url: "http://192.168.1.100:8123"

  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

  auth_providers:
    - type: homeassistant

recorder: !include recorder.yaml

frontend:

config:

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxies
  ip_ban_enabled: true
  login_attempts_threshold: 5

updater:

conversation:

history:

logbook:

map:

sun:

system_health:

wake_on_lan:

person:

tts:
  - platform: google_translate
    service_name: google_say
    language: 'pl'

ifttt:
  key: !secret ifttt_key

media_player: !include_dir_list integrations/media_player

mqtt:
  broker: 172.19.0.20
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_pass

sensor: !include_dir_merge_list entities/sensors
binary_sensor: !include_dir_merge_list entities/binary_sensors
switch: !include_dir_merge_list entities/switch
light: !include_dir_merge_list entities/light
group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
zone: !include zones.yaml
scene: !include scenes.yaml
climate: !include climate.yaml

# input
input_select: !include entities/input_select.yaml
input_number: !include entities/input_number.yaml
input_boolean: !include entities/input_boolean.yaml

google_assistant: !include google_assistant.yaml

# Calendar
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

proximity: !include proximity.yaml

vacuum: !include_dir_list integrations/vacuum

mobile_app:

tplink:
  discovery: false
  switch:
    - host: 192.168.1.121
    - host: 192.168.1.122

yeelight:
  devices: !include_dir_merge_named entities/yeelight

discovery:
  ignore:
    - yeelight

speedtestdotnet: !include integrations/speedtest.yaml

webostv: !include integrations/webostv.yaml

timer: !include_dir_merge_named entities/timer

spotify:
  client_id: !secret spotify_client
  client_secret: !secret spotify_secret