- alias: Vacuum - on via notification
  trigger:
    - event_data:
        action: vacuum_on
      event_type: html5_notification.clicked
      platform: event
  action:
    - service: homeassistant.turn_off
      data_template:
        entity_id: script.vacuum_stop
    - service: automation.trigger
      data_template:
        entity_id: automation.vacuum_on