###################
# Stereo switches #
###################

- platform: mqtt
  name: "Stereo mqtt"
  command_topic: "stereo/on"
  icon: mdi:speaker

- platform: template
  switches:
    stereo:
      friendly_name: "Stereo"
      value_template: "{{ is_state('switch.stereo_mqtt', 'on') }}"
      turn_on:
        service: script.stereo_on
      turn_off:
        service: script.stereo_off
      icon_template: mdi:speaker
