- platform: darksky
  api_key: !secret dark_sky
  forecast:
    - 0
  monitored_conditions:
    - uv_index
    - visibility
    - cloud_cover
    - temperature
    - apparent_temperature
  units: "si"