- platform: rest
  name: SpaceX
  json_attributes:
    - mission_name
    - launch_site
    - rocket
  value_template: '{{ value_json["launch_date_unix"] }}'
  resource: 'https://api.spacexdata.com/v2/launches/next'

- platform: template
  sensors:
    spacex_next_launch_day:
      friendly_name: 'Następny start'
      value_template: '{{ states.sensor.spacex.state | int | timestamp_custom("%d.%m.%Y")}}'
    spacex_next_launch_time:
      friendly_name: 'Czas startu'
      value_template: '{{ states.sensor.spacex.state | int | timestamp_custom("%H:%M")}}'
      unit_of_measurement: 'h'
    spacex_next_rocket:
      friendly_name: 'Nazwa rakiety'
      value_template: '{{ states.sensor.spacex.attributes["rocket"]["rocket_name"] }}'
    spacex_next_launch_site:
      friendly_name: 'Start z'
      value_template: '{{ states.sensor.spacex.attributes["launch_site"]["site_name"] }}'
    spacex_next_mission_name:
      friendly_name: 'Nazwa misji'
      value_template: '{{ states.sensor.spacex.attributes["mission_name"] }}'