- platform: sql
  queries:
    - name: DB size
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="uw482" GROUP BY table_schema;'
      column: 'value'
      unit_of_measurement: kB