- platform: history_stats
  name: Michal work yesterday
  entity_id: person.michal
  state: 'praca'
  type: time
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    hours: 24

- platform: history_stats
  name: Michal work today
  entity_id: person.michal
  state: 'praca'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'