- platform: history_stats
  name: Michal work yesterday
  entity_id: person.michal
  state: 'work'
  type: time
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    hours: 24

- platform: history_stats
  name: Michal work today
  entity_id: person.michal
  state: 'work'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Michal work this week
  entity_id: person.michal
  state: 'work'
  type: time
  start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Michal work last week
  entity_id: person.michal
  state: 'work'
  type: time
  start:  '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 - 7*86400 }}'
  duration:
    days: 5