- platform: history_stats
    name: Michal at work yesterday
    entity_id: person.michal
    state: 'work'
    type: time
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24