- platform: template
  sensors:
    sleep_alarm:
      friendly_name: "sleep alarm"
      value_template: >
        {{ states.input_number.alarm_hour.state | int == now().hour | int 
          and states.input_number.alarm_minute.state | int + 10 == now().minute | int
        }}