- platform: template
  sensors:
    sleep_alarm:
      friendly_name: "sleep alarm"
      value_template: >-
        {{states('input_number.alarm_hour')|int == now().hour
          and states('input_number.alarm_minute')|int + 10 == now().minute
        }}