###########################
# airly caqi level sensor #
###########################

- platform: template
  sensors:
    airly_caqi_level:
      value_template: "{{ states.sensor.dom_caqi.attributes.level }}"