- alias: Vacuum - on via notification
  trigger:
  - event_data:
      action: vacuum_on
    event_type: fcm_android_notifications.clicked
    platform: event
  action:
    - service: automation.trigger
      data_template:
        entity_id: automation.vacuum_on

- alias: Guest mode - off via notification
  trigger:
  - event_data:
      action: guest_mode_off
    event_type: fcm_android_notifications.clicked
    platform: event
  action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: input_boolean.guest_mode