apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: homeassistant
  labels:
    app: mosquitto
spec:
  ports:
  - name: mosquitto-mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
  - name: mosquitto-emc2
    protocol: TCP
    port: 9001
    targetPort: 9001
  selector:
    app: mosquitto
  type: ClusterIP
