########################
# Presence automations #
########################

- id: away_home_script
  alias: Presence automations - away home
  trigger:
    - platform: state
      entity_id: input_boolean.michal_home
      from: 'on'
      to: 'off'
  action:
    - service: script.off_all