- alias: "Notification security - failed login attempt"
  trigger:
    - platform: state
      entity_id: persistent_notification.httplogin
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state != 'None' }}"
  action:
    - service: notify.mobile_app_oneplus_a6013
      data:
        message: "{{ states.persistent_notification.httplogin.attributes.message }}"
    - service: persistent_notification.create
      data:
        title: "{{ states.persistent_notification.httplogin.attributes.message }}"
        message: 'url: https://whatismyipaddress.com/ip/{{ states.persistent_notification.httplogin.attributes.message.split ("from ") [1]}}'
        notification_id: "failed_login"