####################################
# Event starting in an hour sensor #
####################################

- platform: template
  sensors:
    event_hour_offset:
      friendly_name: "Event hour offset"
      value_template: >
        {{ is_state('binary_sensor.event_hour_offset_def', 'on') }}

    event_hour_offset_def:
      friendly_name: "Event hour offset def"
      value_template: >
        {% if states.calendar.michalchecinski1gmailcom.attributes.start_time != none %}
          {{
            ((as_timestamp(states.calendar.michalchecinski1gmailcom.attributes.start_time) - as_timestamp( strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M" ) ) <= 3600 )
            and (as_timestamp(states.calendar.michalchecinski1gmailcom.attributes.end_time) - as_timestamp(states.calendar.michalchecinski1gmailcom.attributes.start_time) >= 3600 )
            and states.calendar.michalchecinski1gmailcom.attributes.all_day == False )
          }}
        {% else %}
          False
        {% endif %}