######################
# Sleep alarm sensor #
######################

- platform: template
  sensors:
    sleep_alarm:
      friendly_name: "sleep alarm"
      value_template: >-
        {{ states('sensor.alarm_time') == states('sensor.time') }}