######################
# Sleep alarm sensor #
######################

- platform: template
  sensors:
    sleep_alarm:
      friendly_name: "sleep alarm"
      value_template: >-
        {{ states.sensor.oneplus6t_next_alarm.attributes.time|replace(':00','') == states('sensor.time') }}