esphome:
  name: livingroom-led

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "4f2f020329a50d76c2b945355e804800"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Desk-Led Fallback Hotspot"
    password: "WTybEqfe8Ets"

captive_portal:

light:
  - platform: binary
    name: "RTV LED"
    output: light_rtv_led
    
  - platform: binary
    name: "TV LED"
    output: light_tv_led
    
output:
  - id: light_rtv_led
    platform: gpio
    pin: D2
    inverted: true

  - id: light_tv_led
    platform: gpio
    pin: RX
    inverted: true
    
sensor:
  - platform: dht
    pin: D4
    temperature:
      name: "Livingroom Temperature"
    humidity:
      name: "Livingroom Humidity"
    update_interval: 60s