name: check config

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Home Assistant Configuration Check
        uses: ludeeus/action-ha-config-check@0.0.1
