name: Home Assistant CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  home_assistant_stable:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Copy secrets
        run: cp travis_secrets.yaml secrets.yaml
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check Config
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --config . --script check_config --info all
  # home_assistant_beta:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Getting your configuration from GitHub
  #       uses: actions/checkout@v1
  #     - name: Copy secrets
  #       run: cp travis_secrets.yaml secrets.yaml
  #     - name: Home Assistant Version
  #       uses: "docker://homeassistant/home-assistant:beta"
  #       with:
  #         args: |
  #           python -m homeassistant --version
  #     - name: Home Assistant Check Config
  #       uses: "docker://homeassistant/home-assistant:beta"
  #       with:
  #         args: python -m homeassistant --config . --script check_config --info all
  # home_assistant_dev:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Getting your configuration from GitHub
  #       uses: actions/checkout@v1
  #     - name: Copy secrets
  #       run: cp travis_secrets.yaml secrets.yaml
  #     - name: Home Assistant Version
  #       uses: "docker://homeassistant/home-assistant:dev"
  #       with:
  #         args: |
  #           python -m homeassistant --version
  #     - name: Home Assistant Check Config
  #       uses: "docker://homeassistant/home-assistant:dev"
  #       with:
  #         args: python -m homeassistant --config . --script check_config --info all