name: check config

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Copy secrets
        run: cp travis_secrets.yaml secrets.yaml

      - name: Install
        run: pip3 install homeassistant

      - name: Check Config
        run: hass -c . --script check_config --info all
