name: Home Assistant CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  home_assistant:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.hass }}
    strategy:
      matrix:
        hass: [homeassistant/home-assistant:stable, homeassistant/home-assistant:rc, homeassistant/home-assistant:dev]
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Copy secrets
        run: cp -a homeassistant/.stubs/. homeassistant/
      - name: Home Assistant Version
        run: python -m homeassistant --version
      - name: Home Assistant Check Config
        run: python -m homeassistant --config ./homeassistant --script check_config --info all
  # home_assistant_beta:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Getting your configuration from GitHub
  #       uses: actions/checkout@v1
  #     - name: Copy secrets
  #       run: cp -a homeassistant/.stubs/. homeassistant/
  #     - name: Home Assistant Version
  #       uses: "docker://homeassistant/home-assistant:beta"
  #       with:
  #         args: |
  #           python -m homeassistant --version
  #     - name: Home Assistant Check Config
  #       uses: "docker://homeassistant/home-assistant:beta"
  #       with:
  #         args: python -m homeassistant --config ./homeassistant --script check_config --info all
  # home_assistant_dev:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Getting your configuration from GitHub
  #       uses: actions/checkout@v1
  #     - name: Copy secrets
  #       run: cp -a homeassistant/.stubs/. homeassistant/
  #     - name: Home Assistant Version
  #       uses: "docker://homeassistant/home-assistant:dev"
  #       with:
  #         args: |
  #           python -m homeassistant --version
  #     - name: Home Assistant Check Config
  #       uses: "docker://homeassistant/home-assistant:dev"
  #       with:
  #         args: python -m homeassistant --config ./homeassistant --script check_config --info all

  deploy:
    if: success() && contains(github.ref, 'master')
    needs: home_assistant_stable
    runs-on: ubuntu-latest
    steps:
      - name: Deploy config
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.SERV_SSH_LOGIN }}
          privateKey: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          command: ssh ${{ secrets.DEPLOYMENT_SSH_LOGIN }}